//Final Project : "CRYPTOGRAPHY SYSTEM"
//Name: MANOOSH SAMIEI 
//Student No:94242070
/*!!!!!ATTENTION!!!!!: Please do not enter the numbers 
on the keypad too quickly! because it leads to system's confusion!
press the next number after the first one is completely turned to a '*' shape!  */


#include <delay.h>
#include <mega32.h>
#include <alcd.h>
#include <stdio.h>
#include <stdlib.h>

unsigned char str[20];//string used for printing keypad number on the lcd
unsigned char key;//keypad number
unsigned char data[4]={0x00,0x00,0x00,0x00};//the entered password
unsigned char pass[4]={0x01,0x03,0x09,0x06};//the right password
unsigned char t,c,b,a,compare=0;
char i,k,j=0;


// Timer 0 output compare interrupt service routine
interrupt [TIM0_COMP] void timer0_comp_isr(void)
{
compare++;
if(compare==2){
t++;  //t will be 500 ms 
compare=0;}
}

#define ADC_VREF_TYPE 0x20

// Read the AD conversion result
unsigned int read_adc(unsigned char adc_input)
{
ADMUX=adc_input | (ADC_VREF_TYPE & 0xff);
// Delay needed for the stabilization of the ADC input voltage
delay_us(10);
// Start the AD conversion
ADCSRA|=0x40;
// Wait for the AD conversion to complete
while ((ADCSRA & 0x10)==0);
ADCSRA|=0x10;
return ADCH;
}


void keyboard (void){   // keypad function
PORTD.0=0;
delay_ms(2);
if(PIND.3==0){key=1;}
if(PIND.4==0){key=4;}
if(PIND.5==0){key=7;}
if(PIND.6==0){ //holding key '*' for 1 sec
delay_ms(1000); 
 if(PIND.6==0){
 key='*';}}
PORTD.0=1;

PORTD.1=0;
delay_ms(2);
if(PIND.3==0){key=2;}
if(PIND.4==0){key=5;}
if(PIND.5==0){key=8;}
if(PIND.6==0){key=0;}
PORTD.1=1;

PORTD.2=0;
delay_ms(2);
if(PIND.3==0){key=3;}
if(PIND.4==0){key=6;}
if(PIND.5==0){key=9;}
if(PIND.6==0){key='#';}
PORTD.2=1;
}

interrupt [EXT_INT2] void ext_int2_isr(void) //interrupt function
{
    #asm("cli");
    PORTD=0x7F;
    keyboard();
    PORTD=0x78;
    #asm("sei");
}


void readpass (void){ //receiving password from user
     while(1){
      if(key!=10){
      if(i==0){
      lcd_clear();}

      lcd_gotoxy(i,0);
      sprintf(str,"%d",key);
      lcd_puts(str);
      t=0;        //500 ms delay generated by timer 0 in compare match mode
      compare=0;
      while(t<1){;}  
      lcd_gotoxy(i,0);
      lcd_putchar('*');   
      data[i]=key;
      i++; 
      key=10;}
       
      if(i==4){   //when all 4 digits of password are received break occurs and loop is ended
      i=0;
      break;}
      
      }
       }

void checkpass (void){    //checking the password

      for(j=0;j<4;j++){  //comparing each component of the two arrays
      if(data[j]==pass[j])
      k++;//if all components are the same k will be equal to 4 
      } 
      
      } 

void main(void)
{
char m=0;
key=20; 

// Input/Output Ports initialization
// Port A initialization
// Func7=In Func6=In Func5=In Func4=In Func3=In Func2=In Func1=In Func0=In 
// State7=T State6=T State5=T State4=T State3=T State2=T State1=T State0=T 
PORTA=0x0F;
DDRA=0x00;

// Port B initialization
// Func7=In Func6=In Func5=In Func4=In Func3=In Func2=In Func1=In Func0=In 
// State7=T State6=T State5=T State4=T State3=T State2=T State1=T State0=T 
PORTB=0x00;
DDRB=0x00;

// Port C initialization
// Func7=In Func6=In Func5=In Func4=In Func3=In Func2=In Func1=In Func0=In 
// State7=T State6=T State5=T State4=T State3=T State2=T State1=T State0=T 
PORTC=0x00;
DDRC=0xFF;

// Port D initialization
// Func7=In Func6=In Func5=In Func4=In Func3=In Func2=Out Func1=Out Func0=Out 
// State7=P State6=P State5=P State4=P State3=P State2=0 State1=0 State0=0 
PORTD=0x78;
DDRD=0x07;

// Timer/Counter 0 initialization
// Clock source: System Clock
// Clock value: 0.977 kHz
// Mode: CTC top=OCR0
// OC0 output: Disconnected
TCCR0=0x0D;
TCNT0=0x00;
OCR0=0xF5;

// External Interrupt(s) initialization
// INT0: Off
// INT1: Off
// INT2: On
// INT2 Mode: Rising Edge
GICR|=0x20;
MCUCR=0x00;
MCUCSR=0x40;
GIFR=0x20;

// Timer(s)/Counter(s) Interrupt(s) initialization
TIMSK=0x02;

// ADC initialization
// ADC Clock frequency: 500.000 kHz
// ADC Voltage Reference: AREF pin
ADMUX=ADC_VREF_TYPE & 0xff;
ADCSRA=0x81;

// Alphanumeric LCD initialization
// Connections are specified in the
// Project|Configure|C Compiler|Libraries|Alphanumeric LCD menu:
// RS - PORTC Bit 0
// RD - PORTC Bit 1
// EN - PORTC Bit 2
// D4 - PORTC Bit 4
// D5 - PORTC Bit 5
// D6 - PORTC Bit 6
// D7 - PORTC Bit 7
// Characters/line: 16
lcd_init(16);
lcd_clear();
// Global enable interrupts
#asm("sei")

while (1)
      {
       
    
      if(key==20){ //if no key is pressed, lcd shows "enter password"
      lcd_gotoxy(3,0);
      lcd_puts("enter pass");}
      
      if(key!=20 && key!=10){
      if(key!='#' && key!='*'){ //receiving password from the user
      readpass();
      } }
      
      if(key=='#'){  //comparing the entered password with the right one   
      k=0;
      checkpass();
      
      if(k==4){   // if k is qual to 4 the entered number is equal to the right password
      lcd_clear();
      lcd_putsf("correct");//"correct" is showed on the lcd 
      key=10; //it does not enter any if loop, unitl no number is pressed on the key pad; it means that I allowed the users to enter the passsword as many times as they want even if the right one was entered previously 
      i=0; //in case of entering the password again it helps the program to function correctly (the right place of the cursor)
      k=0;}
      
      else { //if the entered number is not equal to the right password 
      t=0; // locking the system for 30 seconds generated by timer 0 
      compare=0; 
      lcd_putsf("incorrect");
      GICR&=0x1f; //disabling the external interrupt( locking the keyboard and the system)
      while(t<60){;}
      GICR|=0x20;
      lcd_clear();   
      key=20; // to show"enter password" on lcd
      i=0;  // fixing cursor right location
      k=0;} 
      }
      
      if(key=='*'){ //changing the password 
      lcd_clear();
      lcd_putsf("old pass?"); 
      key=10;
      readpass();
      checkpass(); //check if user has entered the old password correctly 
      delay_ms(200); //slowing the process , it can also be produced by the timer but for avoiding the program from being too lengthy I avoided using timer 
      if(k==4){
      lcd_clear();
      delay_ms(200);
      lcd_putsf("new pass?");
      readpass();     //receiving new password from user
      for(m=0;m<4;m++){
      pass[m]=data[m]; //putting the new password into the old password
      }  
      key=20;     //check if the new password works correctly
      lcd_clear();
      delay_ms(200);
      }
      
      else if(k!=4){  // if the old password is not entered correctly goes to the first state: "enter password"
      key=20;
      lcd_clear();}
      }
      
      a=read_adc(0); //reseting password by applying a 2 volt voltage difference between pins adc0 and adc1
      b=read_adc(1);  
      c=cabs(a-b);  // absolute value of a & b difference
      if(c==102){ // 2*255/5 , vref is 5 volts
      key=10;
      lcd_gotoxy(3,0);
      lcd_putsf("reset pass");}

      }
}
